### ISSUE TITLE
Bamboo Artifactory Plugin Issue

### ISSUE THREAD

**Issue by PrathimaAltisource** [jfrog/bamboo-artifactory-plugin#167]
**Describe the [bug**]([url](url))
BAmboo Artifactory Plugin issue 

**To Reproduce**
We are connecting BAmboo Artificatory Plugin 3.2.5 earlier which was working as expected in our Bamboo Server version 8.0.4.Today all of a sudden there is update for Bamboo Artifactory Plug-in to 3.2.6 and when updated it throws issue .

2022-01-31 02:23:40,141 INFO [http-nio-8085-exec-36] [PluginSettingsAuditLogService] Mon Jan 31 02:23:40 EST 2022 gujjarla: Failed to enable app Bamboo Artifactory Plugin (org.jfrog.bamboo.bamboo-artifactory-plugin)
**Expected behavior**

**Screenshots**
PFA
<img width="960" alt="EnablingPlugin" src="https://user-images.githubusercontent.com/98740236/151772978-7cdde949-232c-4924-a4b3-e1a73409a919.png">
<img width="960" alt="IssueinJob" src="https://user-images.githubusercontent.com/98740236/151773000-c836f2aa-c142-47c8-b023-4eb742d4dc32.png">

**Versions**
- Bamboo Artifactory plugin version: 3.2.6
- Bamboo operating system: RHEL7
- Artifactory Version:Commercial license 7.7.8 

**Additional context**

**Comment by PrathimaAltisource** [comment]
This is production issue and stuckup with this.

**Comment by yahavi** [comment]
@PrathimaAltisource,
Thanks for reporting this issue!

As it looks, the plugin is not installed on your agent. This may occur due to many reasons. Please try to reinstall the plugin and check the agent's logs.

For example, one possible reason is the lack of memory in the agent. If you see errors such as:

    INFO | jvm 1 | 2020/11/10 11:12:36 | 2020-11-10 11:12:36,120 ERROR [remoteEventRebroadcasterMessageListenerContainer-1] [ScanningPluginLoader] Unable to deploy plugin 'org.jfrog.bamboo.bamboo-artifactory-plugin' from 'Unit: /Users/yahavi/bamboo-agent-home/plugins/user-installed/plugin_8527020839401694412_bamboo-artifactory-plugin-3.1.0.jar (1604999532000)'.
    INFO | jvm 1 | 2020/11/10 11:12:36 | 2020-11-10 11:12:36,121 ERROR [remoteEventRebroadcasterMessageListenerContainer-1] [ScanningPluginLoader] Because of the following exception:
    INFO | jvm 1 | 2020/11/10 11:12:36 | java.lang.OutOfMemoryError: GC overhead limit exceeded

That means your agent has insufficient heap size. I'd recommend on the resolution in this guide: https://confluence.atlassian.com/bamkb/outofmemory-errors-in-bamboo-server-or-in-remote-agent-307038120.html

Please let me know if it helped.

**Comment by PrathimaAltisource** [comment]
All the Plugins are Installed on BAmboo Server UI and not Agent .And this also installed on MAnage apps>> Install Bamboo artifactory plugin
How to install on Bamboo agent..

**Comment by PrathimaAltisource** [comment]
On Agent the wrapper.conf has these values.
# Restart agent only if it has exited with code other than 0
wrapper.on_exit.0=SHUTDOWN
wrapper.on_exit.default=RESTART

# Initial Java Heap Size (in MB)
wrapper.java.initmemory=512

# Maximum Java Heap Size (in MB)
wrapper.java.maxmemory=1024

**Comment by yahavi** [comment]
@PrathimaAltisource 
Thanks for the information.
Could you please try to increase the java heap size in the agent? For example:
```yaml
wrapper.java.initmemory=1024
wrapper.java.maxmemory=2048
```

**Comment by PrathimaAltisource** [comment]
Ok.. Does this plugin depends on Agent ? But  nothgin in the agent log seems to be issue ..

Ok let me give a try to add these and does this require restart of bamboo server / agents ?

**Comment by PrathimaAltisource** [comment]
I have added in wrapper.conf and restarted BAmboo server application and again tried to enable the Plugin.. Same issue

**Comment by PrathimaAltisource** [comment]
This is Production issue which is causing huge impact.. Any help here would be appreciated..

**Comment by yahavi** [comment]
@PrathimaAltisource,
Thanks for your input.

The change in 3.2.6 was minor: https://github.com/jfrog/bamboo-artifactory-plugin/compare/3.2.5...3.2.6. I'm not sure it caused the issue. In former cases, issues like that were resolved after increasing the agent's memory, **uninstalling**, and **installing** the Bamboo Artifactory plugin. 
If this is the case, disabling and enabling the plugin wouldn't help, since there is an installation error in the agent. Only **reinstalling** would do.

It could be also that the server is out of memory. Here are instructions for how to increase it: https://confluence.atlassian.com/bamkb/outofmemory-errors-on-the-bamboo-server-or-local-agent-82870484.html.

Either way, I suggest inspecting the logs, looking for any errors.

If all of the above didn't help, you can try to install a former version of the plugin. You can download Bamboo Artifactory plugin 3.2.5 from [here](https://releases.jfrog.io/artifactory/oss-release-local/org/jfrog/bamboo/bamboo-artifactory-plugin/3.2.5/bamboo-artifactory-plugin-3.2.5.jar).
Please let me know if that helped.

**Comment by PrathimaAltisource** [comment]
The version of 3.2.5 which was earlier asked to update the Plugin and when updated from 3.2.5 it stopped working with belwo issue.

Tried Installing, unsitalling 3.2.3, 3.2.4,3.2.5 ,3.2.6 they are installing , but when enabling we are getting below error.  

d by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy1971
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739)
        at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:126)
        at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110)
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ProxyUtils.createProxy(ProxyUtils.java:68)
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ProxyUtils.createProxy(ProxyUtils.java:37)
        at org.eclipse.gemini.blueprint.service.importer.support.AbstractServiceProxyCreator.createServiceProxy(AbstractServiceProxyCreator.java:105)
        at org.eclipse.gemini.blueprint.service.importer.support.OsgiServiceProxyFactoryBean.createProxy(OsgiServiceProxyFactoryBean.java:176)
        at org.eclipse.gemini.blueprint.service.importer.support.AbstractServiceImporterProxyFactoryBean.getObject(AbstractServiceImporterProxyFactoryBean.java:95)
        at org.eclipse.gemini.blueprint.service.importer.support.OsgiServiceProxyFactoryBean.getObject(OsgiServiceProxyFactoryBean.java:122)
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
        ... 15 more
2022-01-31 07:14:18,603 INFO [http-nio-8085-exec-27] [PluginSettingsAuditLogService] Mon Jan 31 07:14:18 EST 2022 gujjarla: Failed to enable app Bamboo Artifactory Plugin (org.jfrog.bamboo.bamboo-artifactory-plugin)

**Comment by PrathimaAltisource** [comment]
<img width="960" alt="EnablingPlugin1" src="https://user-images.githubusercontent.com/98740236/151792840-079cd1f4-7176-46bc-919f-084078c2bbf7.png">

**Comment by mandevs** [comment]
we stuck with the same issue, Is there any workaround till we get this fixed?

**Comment by eyalbe4** [comment]
@mandevs -
See @yahavi 's comment above. Do you see the ```java.lang.OutOfMemoryError```  anywhere in the server logs? If you do - this is the cause of the problem.
