### ISSUE TITLE
Artifactory plugin 3.2.9 for Bamboo does not work in Bamboo 9.0

### ISSUE THREAD

**Issue by tibormarchynzoom** [jfrog/bamboo-artifactory-plugin#188]
**Describe the bug**
Artifactory plugin 3.2.9 for Bamboo is not loading and never start up in Bamboo 9.0

```
2022-09-04 12:58:26,604 ERROR [ThreadPoolAsyncTaskExecutor::Thread 34] [OsgiPlugin] Unable to start the plugin container for plugin 'org.jfrog.bamboo.bamboo-artifactory-plugin'
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userManager': FactoryBean threw exception on object creation; nested exception is java.lang.NoClassDefFoundError: Could not initiali
ze class com.sun.proxy.$Proxy2152
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:176) ~[spring-beans-5.3.21.jar:5.3.21]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101) ~[spring-beans-5.3.21.jar:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1884) ~[spring-beans-5.3.21.jar:5.3.21]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1284) ~[spring-beans-5.3.21.jar:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:267) ~[spring-beans-5.3.21.jar:5.3.21]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.21.jar:5.3.21]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:950) ~[spring-beans-5.3.21.jar:5.3.21]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.21.jar:5.3.21]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.access$1600(AbstractDelegatedExecutionApplicationContext.java:57) ~[?:?]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext$4.run(AbstractDelegatedExecutionApplicationContext.java:322) ~[?:?]
        at org.eclipse.gemini.blueprint.util.internal.PrivilegedUtils.executeWithCustomTCCL(PrivilegedUtils.java:85) ~[?:?]
        at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.completeRefresh(AbstractDelegatedExecutionApplicationContext.java:287) ~[?:?]
        at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor$CompleteRefreshTask.run(DependencyWaiterApplicationContextExecutor.java:137) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_322]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_322]
        at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.proxy.$Proxy2152
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_322]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_322]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_322]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_322]
        at java.lang.reflect.Proxy.newProxyInstance(Proxy.java:739) ~[?:1.8.0_322]
        at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:126) ~[spring-aop-5.3.21.jar:5.3.21]
        at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:110) ~[spring-aop-5.3.21.jar:5.3.21]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ProxyUtils.createProxy(ProxyUtils.java:68) ~[?:?]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ProxyUtils.createProxy(ProxyUtils.java:37) ~[?:?]
        at org.eclipse.gemini.blueprint.service.importer.support.AbstractServiceProxyCreator.createServiceProxy(AbstractServiceProxyCreator.java:105) ~[?:?]
        at org.eclipse.gemini.blueprint.service.importer.support.OsgiServiceProxyFactoryBean.createProxy(OsgiServiceProxyFactoryBean.java:176) ~[?:?]
        at org.eclipse.gemini.blueprint.service.importer.support.AbstractServiceImporterProxyFactoryBean.getObject(AbstractServiceImporterProxyFactoryBean.java:95) ~[?:?]
        at org.eclipse.gemini.blueprint.service.importer.support.OsgiServiceProxyFactoryBean.getObject(OsgiServiceProxyFactoryBean.java:122) ~[?:?]
        at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169) ~[spring-beans-5.3.21.jar:5.3.21]
        ... 15 more
```

**To Reproduce**
Upgrade Bamboo to version 9.0

**Expected behavior**
Artifactory plugin 3.2.9 for Bamboo successfully start up in Bamboo 9.0

**Versions**
- Bamboo Artifactory plugin version: 3.2.9
- Bamboo operating system: CentOS 8 Stream
- Artifactory Version: 7.41.12
- Bamboo Version: 9.0.0

**Comment by mattquila** [comment]
Ran into the same issue

To Reproduce
Upgrade Bamboo to version 9.0

Expected behavior
Artifactory plugin 3.2.9 for Bamboo successfully start up in Bamboo 9.0

Versions

Bamboo Artifactory plugin version: 3.2.9
Bamboo operating system: Windows 2016
Artifactory Version: 7.35.2
Bamboo Version: 9.0.0

**Comment by RobiNino** [comment]
Hi @tibormarchynzoom @mattquila @Sven-O,
Bamboo Artifactory plugin version 3.3.0 was just released and is compatible with Bamboo 9.2.1.
We'd appreciate your feedback for it.
Thank you for your patience.
